import json
from pathlib import Path
from uuid import uuid4

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from services.chat_engine import answer_question
from services.embedding_store import chunk_text, create_embeddings
from services.paper_processor import process_paper
from services.vector_db import clear_db, store_embeddings


app = FastAPI(title="Research Paper Analyzer - Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR = Path("data")
RAW_PAPERS_DIR = DATA_DIR / "raw_papers"
PROCESSED_DIR = DATA_DIR / "processed_text"

RAW_PAPERS_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

CURRENT_PAPER: dict | None = None


class ChatRequest(BaseModel):
    question: str
    top_k: int = 3


def _save_processed_paper(paper_data: dict) -> None:
    output_path = PROCESSED_DIR / f"{paper_data['paper_id']}.json"
    output_path.write_text(json.dumps(paper_data, indent=2), encoding="utf-8")


def _set_current_paper(paper_data: dict) -> None:
    global CURRENT_PAPER
    CURRENT_PAPER = paper_data


def _get_current_paper() -> dict:
    if CURRENT_PAPER is None:
        raise HTTPException(status_code=404, detail="No paper uploaded yet")
    return CURRENT_PAPER


def _index_paper_for_chat(paper_data: dict) -> int:
    full_text = paper_data.get("full_text", "").strip()
    if not full_text:
        sections = paper_data.get("sections", {})
        full_text = " ".join(sections.values()).strip()

    if not full_text:
        raise HTTPException(status_code=400, detail="No extractable text found in uploaded paper")

    clear_db()
    chunks = chunk_text(full_text, chunk_size=300, overlap=50)
    embeddings = create_embeddings(chunks)
    store_embeddings(chunks, embeddings)
    return len(chunks)


@app.post("/upload")
async def upload_paper(file: UploadFile = File(...)):
    """Upload a PDF, run Person A's NLP pipeline, and index it for chat."""
    filename = file.filename or ""
    if not filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported")

    paper_id = str(uuid4())
    file_path = RAW_PAPERS_DIR / f"{paper_id}.pdf"
    file_bytes = await file.read()
    if not file_bytes:
        raise HTTPException(status_code=400, detail="Uploaded PDF is empty")

    file_path.write_bytes(file_bytes)

    try:
        paper_data = process_paper(file_path)
        paper_data["paper_id"] = paper_id
        chunks_stored = _index_paper_for_chat(paper_data)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to process PDF: {exc}") from exc

    _save_processed_paper(paper_data)
    _set_current_paper(paper_data)

    return {
        "status": "success",
        "paper_id": paper_id,
        "chunks_stored": chunks_stored,
        "metadata": paper_data.get("metadata", {}),
        "summaries": paper_data.get("summaries", {}),
        "keywords": paper_data.get("keywords", []),
        "concepts": paper_data.get("concepts", []),
    }


@app.post("/chat")
def chat(request: ChatRequest):
    """Answer a question about the uploaded paper."""
    paper = _get_current_paper()
    try:
        result = answer_question(request.question, top_k=request.top_k)
        return {
            "paper_id": paper["paper_id"],
            "question": request.question,
            "answer": result["answer"],
            "sources": result["context"],
        }
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Chat model failed: {exc}") from exc


@app.get("/metadata")
def get_metadata():
    """Return metadata for the currently loaded paper."""
    paper = _get_current_paper()
    return {
        "paper_id": paper["paper_id"],
        "metadata": paper.get("metadata", {}),
    }


@app.post("/summarize")
def summarize():
    """Return summaries generated by Person A during upload."""
    paper = _get_current_paper()
    return {
        "paper_id": paper["paper_id"],
        "summaries": paper.get("summaries", {}),
    }


@app.get("/keywords")
def get_keywords():
    """Return keywords and concepts for the currently loaded paper."""
    paper = _get_current_paper()
    return {
        "paper_id": paper["paper_id"],
        "keywords": paper.get("keywords", []),
        "keyword_details": paper.get("keyword_details", []),
        "concepts": paper.get("concepts", []),
    }


@app.get("/paper")
def get_paper():
    """Return the full processed JSON for the currently loaded paper."""
    return _get_current_paper()


@app.get("/health")
def health():
    """Simple health endpoint for local development."""
    return {
        "status": "ok",
        "paper_loaded": CURRENT_PAPER is not None,
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
